name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t abhi4124/ahhhbot:${{ github.event.release.tag_name }} .
        
      - name: Tag Docker image as latest
        run: docker tag abhi4124/ahhhbot:${{ github.event.release.tag_name }} abhi4124/ahhhbot:latest

      - name: Push Docker images
        run: |
          docker push abhi4124/ahhhbot:${{ github.event.release.tag_name }}
          docker push abhi4124/ahhhbot:latest
